spring.application.name=Pull-Request-Service
logging.level.root=INFO
logging.level.com.personalprojects.pullrequestservice=DEBUG
github.webhook.secret=${WEBHOOK_SECRET}

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=false

logging.level.io.netty.resolver.dns.DnsServerAddressStreamProviders=FATAL